FROM ubuntu:20.04

RUN apt-get update && apt-get install -y python3-pip

RUN echo "pyxtermjs" >> requirements.txt

RUN yes | pip install -r requirements.txt

EXPOSE 5000

CMD ["python3", "-m", "pyxtermjs", "--host", "0.0.0.0"]
